# Homework 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [1]:
import numpy as np
mat = np.full((4, 4), 7)
for i in range(len(mat)):
    mat[i][i] = i + 1
mat

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
np.array([np.arange(0,5), np.arange(0,5), np.arange(0,5), np.arange(0,5), np.arange(0,5)])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [14]:
mat = np.random.randint(0, 100, (10, 10))
sub = mat.mean(axis=1)
print(mat)
mat = (mat.transpose() - sub).transpose()
print(mat)
print(sub)


[[ 0  6 54 75 78 51 42 42 33 97]
 [74 61 43 58 14 25  9 24 94 90]
 [80 45 96  0  6 67  6 78 73  6]
 [92 72 56 90 40 79 71 97  2 92]
 [97 24 39 50 51 79  7 20 67 45]
 [62 54 96 93 46 59 36 40 91 31]
 [31 67 16 32 86 13 48 79  8 87]
 [55 33 59 85 83 62 81 49 80 87]
 [ 6 21 73 11 78 14 64 22 41 88]
 [84 83  7 84 36 53 18 12 88 85]]
[[-47.8 -41.8   6.2  27.2  30.2   3.2  -5.8  -5.8 -14.8  49.2]
 [ 24.8  11.8  -6.2   8.8 -35.2 -24.2 -40.2 -25.2  44.8  40.8]
 [ 34.3  -0.7  50.3 -45.7 -39.7  21.3 -39.7  32.3  27.3 -39.7]
 [ 22.9   2.9 -13.1  20.9 -29.1   9.9   1.9  27.9 -67.1  22.9]
 [ 49.1 -23.9  -8.9   2.1   3.1  31.1 -40.9 -27.9  19.1  -2.9]
 [  1.2  -6.8  35.2  32.2 -14.8  -1.8 -24.8 -20.8  30.2 -29.8]
 [-15.7  20.3 -30.7 -14.7  39.3 -33.7   1.3  32.3 -38.7  40.3]
 [-12.4 -34.4  -8.4  17.6  15.6  -5.4  13.6 -18.4  12.6  19.6]
 [-35.8 -20.8  31.2 -30.8  36.2 -27.8  22.2 -19.8  -0.8  46.2]
 [ 29.   28.  -48.   29.  -19.   -2.  -37.  -43.   33.   30. ]]
[47.8 49.2 45.7 69.1 47.9 60.8 46.7 67

4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [15]:
mat = np.random.randint(0, 100, (10, 10))
print(mat)
sub = np.median(mat, axis=0)
mat = mat - sub
print(mat)

print('Медианы: ')
print(sub)

[[10 54 53 92 28  2 37 73 53 12]
 [ 5 42 67  8 60 49 78 86 72 85]
 [20 81 52 38 91 75 45 21 51 63]
 [68 96 66 88  1 84 81 52 87 63]
 [81 84  0 22 93 44 78 44 19 56]
 [37 42 28 16 44 31  2  5 28 19]
 [ 7 10 12 73 72 67 59 89 81 15]
 [32 53 34 76 49 79 96 11 94 29]
 [82  0 23 38 20 19 74 82 34 10]
 [32 38 15 24 63 69 48 65 43 33]]
[[-22.    6.5  22.   54.  -26.5 -56.  -29.5  14.5   1.  -19. ]
 [-27.   -5.5  36.  -30.    5.5  -9.   11.5  27.5  20.   54. ]
 [-12.   33.5  21.    0.   36.5  17.  -21.5 -37.5  -1.   32. ]
 [ 36.   48.5  35.   50.  -53.5  26.   14.5  -6.5  35.   32. ]
 [ 49.   36.5 -31.  -16.   38.5 -14.   11.5 -14.5 -33.   25. ]
 [  5.   -5.5  -3.  -22.  -10.5 -27.  -64.5 -53.5 -24.  -12. ]
 [-25.  -37.5 -19.   35.   17.5   9.   -7.5  30.5  29.  -16. ]
 [  0.    5.5   3.   38.   -5.5  21.   29.5 -47.5  42.   -2. ]
 [ 50.  -47.5  -8.    0.  -34.5 -39.    7.5  23.5 -18.  -21. ]
 [  0.   -9.5 -16.  -14.    8.5  11.  -18.5   6.5  -9.    2. ]]
Медианы: 
[32.  47.5 31.  38.  54.5 58

5) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [5]:
mat = np.random.randint(0, 100, (5, 5))
max_ = mat.max(axis=1)
min_ = mat.min(axis=1)

max_ = np.array(max_).reshape(5,1)
min_ = np.array(min_).reshape(5,1)
mat = np.hstack((mat, max_))
np.hstack((mat, min_))

array([[49, 75, 87, 65, 93, 93, 49],
       [ 4, 70, 74, 65, 27, 74,  4],
       [17, 29, 73, 74, 27, 74, 17],
       [ 5, 60, 35, 87, 47, 87,  5],
       [86, 79, 14, 62,  9, 86,  9]])

6) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [6]:
arr = np.arange(1,51)
arr_odd = arr[arr % 2 != 0]
arr_even = arr[arr % 2 == 0]
arr_odd = arr_odd.reshape((5,-1))
arr_even = arr_even.reshape((-1,5))
A = arr_even * arr_odd
np.linalg.inv(A)

array([[-1.21871343e+13,  2.67820109e+13, -7.22322708e+12,
        -1.71510415e+13,  9.77939191e+12],
       [ 3.49947211e+13, -7.99502395e+13,  2.98823915e+13,
         4.01070508e+13, -2.50339240e+13],
       [-3.18613578e+13,  7.91586529e+13, -4.63078120e+13,
        -1.74149036e+13,  1.64254205e+13],
       [ 7.48708926e+12, -2.55946311e+13,  3.18613578e+13,
        -1.68871793e+13,  3.13336335e+12],
       [ 1.56668167e+12, -3.95793265e+11, -8.21271024e+12,
         1.13460736e+13, -4.30425175e+12]])

7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [7]:
A = np.zeros((8,8))
for i in range(0,16, 2):
    A += np.eye(8, k= i-6)
A

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])