In [10]:
import numpy as np

class Matrix:
    
    def sum_mat(A, B):
        if A.shape == B.shape:
            return A + B
        
        print("Матрицы разной размерности")
        return False
    
    def mult_numb(A,b):
        if isinstance(b, (int, float)):
            return A*b
        
        print("Второй аргумент не число")
        return False
    
    def mult(A,B):
        return np.dot(A,B)
    
    def det(A):
        if len(A) == len(A[0]):
            return np.linalg.det(A)
        
        print("Матрица не квадратная")
        return False
    
    def inverse(A):
        if Matrix.det(A) != 0:
            return np.linalg.inv(A)  
        
        print("Матрица вырожденная")
        return False
    
    def transp(A):
        return A.transpose()
    
    
A = np.array([[0, 1, 5], [5, 2, 1], [0, 0, 1]], float)
B = np.array([[0, 1, -6], [0, -8, 1], [14, 9, 2]], float)
print(Matrix.det(A))
print(Matrix.inverse(A))
print(Matrix.transp(A))
print(Matrix.sum_mat(A, B))
print(Matrix.mult_numb(A, '1'))

-4.999999999999999
[[-0.4  0.2  1.8]
 [ 1.   0.  -5. ]
 [ 0.   0.   1. ]]
[[0. 5. 0.]
 [1. 2. 0.]
 [5. 1. 1.]]
[[ 0.  2. -1.]
 [ 5. -6.  2.]
 [14.  9.  3.]]
Второй аргумент не число
False


In [68]:
def head(pair):
    if pair is None:
        return None
    return pair[0]

def tail(pair):
    if pair is None:
        return None
    if len(pair) < 2:
        return None
    return pair[1]

def Seq(*elements):
    def first(x):
        return x[0]
    def other(x):
        return x[1:]

    if len(elements) == 0:
        return None

    if len(elements) == 1:
        return first(elements), None

    if len(elements) == 2:
        return first(elements), other(elements)

    return first(elements), Seq(*other(elements))

def at(pair, index):
    if pair is None:
        return None
    
    if index == 0:
        return  pair[0]
    
    if len(pair) < 2:
        return None
    
    index -= 1
    return at(pair[1], index)

def size(pair):
    if pair is None:
        return None
    
    if len(pair) < 2:
        return 1
    
    return 1 + size(pair[1])

def eq(pair1, pair2):
    if (pair1 is None) and (pair2 is None):
        return True
    
    if pair1[0] != pair2[0]:
        return False
    
    if len(pair1) < 2 and len(pair2) < 2:
        return True
    
    if len(pair1) < 2 or len(pair2) < 2:
        return False    
    return eq(pair1[1], pair2[1])

def tailN(pair, N):
    if pair is None:
        return None
    
    if N == 0:
        return  pair
    
    N -= 1
    return tailN(pair[1], N)

def concat(pair1, pair2):
    if (pair1 is None) and (pair2 is None):
        return None
    
    if (pair1 is None):
        return pair2
    
    if (pair2 is None):
        return pair1
    
    if len(pair1) < 2:
        return pair1[0], pair2
    
    return pair1[0], concat(pair1[1], pair2)

def for_each(pair):
    if pair is None:
        return None
    if len(pair) < 2:
        return
    return for_each(pair[1])

#def for_each_indexed 

#def maps( fun = lambda x: x**2, pair):

s = Seq(1,2,3,4,5)
s == (1, (2, (3, (4, (5,)))))
head(s) == 1
tail(s) == (2, (3, (4, (5,))))
at(s, 3) == 4
size((4,)) == 1
eq(s, (1, (2, (3, (4, (5,))))))
tailN(s, 4) 
concat((1,(2,)),(3,(4,(5,)))) == s
for_each(s)

1
2
3
4
5
